In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

from aix360.algorithms.protodash import ProtodashExplainer, get_Gaussian_Data
from aix360.datasets import CDCDataset

In [11]:
test = pd.read_csv('./data/UNSW_NB15_training-set.csv')
train = pd.read_csv('./data/UNSW_NB15_testing-set.csv')

In [27]:
# convert pandas dataframe to numpy
data = train[:10].to_numpy()

#sort the rows by sequence numbers in 1st column 
idx = np.argsort(data[:, 0])  
data = data[idx, :]

# replace nan's (missing values) with 0's
original = data
#original[np.isnan(original)] = 0

# delete 1st column (sequence numbers)
original = original[:, 1:]

# one hot encode all features as they are categorical
onehot_encoder = OneHotEncoder()
onehot_encoded = onehot_encoder.fit_transform(original)

explainer = ProtodashExplainer()

In [30]:
onehot_encoded.toarray().shape

(10, 207)

In [32]:
(W, S, _) = explainer.explain(onehot_encoded.toarray(), onehot_encoded.toarray(), m=5)

In [33]:
inc_prototypes = train[:10].iloc[S, :].copy()
# Compute normalized importance weights for prototypes
inc_prototypes["Weights of Prototypes"] = np.around(W/np.sum(W), 2) 
inc_prototypes

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label,Weights of Prototypes
6,7,0.637109,tcp,-,FIN,10,8,534,354,26.683033,...,40,0,0,0,1,39,0,Normal,0,0.19
4,5,0.449454,tcp,-,FIN,10,6,534,268,33.373826,...,40,0,0,0,2,39,0,Normal,0,0.24
3,4,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,...,3,1,1,0,2,1,0,Normal,0,0.17
1,2,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,...,2,0,0,0,1,6,0,Normal,0,0.18
7,8,0.521584,tcp,-,FIN,10,8,534,354,32.593026,...,40,0,0,0,3,39,0,Normal,0,0.22